config/routes.rb
# frozen_string_literal: true

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  namespace :admin do
    namespace :api do
      post "project/status" => "status_updates#create"
    end

    resource :download, only: %i[show create]
    resource :download_all_users, only: [:show]
    resource :download_all_rmas, only: [:show]

    resources :failed_submissions, only: :index do
      member do
        put :mark_as_submitted
        put :retry_submission
      end
    end

    resources :projects do
      member do
        get :edit
        patch :save
      end
    end

    resources :user_areas, only: [:destroy]
    resources :users do
      member do
        get :reinvite
      end
    end
    resources :confirmations, only: [:index]
    resources :camc3, only: [:show], controller: :camc3
    resources :organisations, only: %i[index new create edit update]
  end
  devise_for :users, controllers: { passwords: "passwords" }

  get "/password/reset" => "reset_password#reset", as: :after_password_reset

  mount PafsCore::Engine, at: "/pc"

  match "(errors)/:status", to: PafsCore::Engine, via: :all, constraints: { status: /\d{3}/ }

  root "admin/users#index"
end
# rubocop:enable Metrics/BlockLength

app/views/shared/_flash_alerts.html.erb
<%
  ## Uncomment the lines below to test the flash alerts
  # %i[alert warn notice info not_authorized].each do |a|
  #   flash[a] = "A flash alert with key [#{a}]"
  # end
  flashes = flash.to_hash.symbolize_keys.slice(:alert, :notice, :info, :warn, :not_authorized)
%>
<% if flashes.any? %>
  <div class="front-office-core-alerts">
    <% flashes.each do |key, messages| %>
        <%
          flash.discard(key)
          clazz =
            case key
            when :alert then "danger"
            when :notice then "success"
            when :info then "info"
            when :warn then "warning"
            when :not_authorized then "danger"
            else "alert"
            end
          messages = [messages] unless messages.is_a?(Array)
        %>

        <% messages.reject(&:blank?).each do |text| %>
          <div class= "govuk-error-summary alert alert-<%= clazz %>" role="alert" >
            <%= text.to_s %>
          </div>
        <% end %>
    <% end %>
  </div>
<% end %>

app/views/shared/_forgotten_email.html.erb
<details>
  <summary>I have forgotten which email address to use</summary>
  <div class="panel">
    <p>If you don't know the email address used to set up your account, contact the Environment Agency on <%= t("support_telephone_number") %>.</p>
  </div>
</details>

app/views/shared/_forgotten_password.html.erb
<details>
  <summary>I have forgotten my password</summary>
  <div class="panel">
    <p>If you don't know the password confirmed to you by email when your account was created, you can <%= link_to t("reset_your_password_link"), new_password_path(resource_name) %></p>
  </div>
</details>

app/views/shared/_phase_banner.html.erb
<div class="phase-banner-beta">
  <p>
    <strong class="phase-tag">BETA</strong>
    <span><%= t(".heading_html", :href => link_to(t(".feedback"), PafsCore.config.banner_feedback_uri)) %></span>
  </p>
</div>

app/views/shared/_user_bar.html.erb
<div class="user-bar govuk-grid-row govuk-body">
  <div class="govuk-grid-column-full">
    <ul class="user-menu govuk-!-font-size-16">
      <li>Signed in as: <%= current_user.full_name %></li>
      <li><%= link_to t("all_projects"), main_app.admin_projects_path %></li>
      <li><%= link_to t("users"), main_app.admin_users_path %></li>
      <li><%= link_to t("download_all_projects"), main_app.admin_download_path %></li>
      <li><%= link_to t("submissions"), main_app.admin_confirmations_path %></li>
      <% if ENV.fetch('POL_FAILURE_NOTIFICATION_EMAIL', false) %>
        <li><%= link_to t("failed_submissions"), main_app.admin_failed_submissions_path %></li>
      <% end %>
      <li><%= link_to(t('logout_link'), main_app.destroy_user_session_path) %></li>
    </ul>
    <ul class="user-menu stacked-menu govuk-!-font-size-16">
      <li><%= link_to t("download_rma_list"), admin_download_all_rmas_path(({:format => :xls})) %></li>
      <li><%= link_to t("add_organisation"), main_app.new_admin_organisation_path %></li>
      <li><%= link_to t("manage_organisations"), main_app.admin_organisations_path %></li>
    </ul>
    <hr class="govuk-section-break govuk-section-break--s govuk-section-break--visible">
  </div>
</div>