config/routes.rb
# frozen_string_literal: true

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  namespace :admin do
    namespace :api do
      post "project/status" => "status_updates#create"
    end

    resource :download, only: %i[show create]
    resource :download_all_users, only: [:show]
    resource :download_all_rmas, only: [:show]

    resources :failed_submissions, only: :index do
      member do
        put :mark_as_submitted
        put :retry_submission
      end
    end

    resources :projects do
      member do
        get :edit
        patch :save
      end
    end

    resources :user_areas, only: [:destroy]
    resources :users do
      member do
        get :reinvite
      end
    end
    resources :confirmations, only: [:index]
    resources :camc3, only: [:show], controller: :camc3
    resources :organisations, only: %i[index new create edit update]
  end
  devise_for :users, controllers: { passwords: "passwords" }

  get "/password/reset" => "reset_password#reset", as: :after_password_reset

  mount PafsCore::Engine, at: "/pc"

  match "(errors)/:status", to: PafsCore::Engine, via: :all, constraints: { status: /\d{3}/ }

  root "admin/users#index"
end
# rubocop:enable Metrics/BlockLength

app/models/organisation.rb
# frozen_string_literal: true

class Organisation < PafsCore::Area
  ORGANISATION_TO_AREA_MAPPING = {
    "Authority" => "Authority",
    "PSO" => "PSO Area",
    "RMA" => "RMA"
  }.freeze

  paginates_per 20
end

app/controllers/admin/organisations_controller.rb
# frozen_string_literal: true

module Admin
  class OrganisationsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_organisation, only: %i[edit update]

    def index
      q = params.fetch(:q, nil)
      type = params.fetch(:type, Organisation::RMA_AREA)
      page = params.fetch(:page, "1").to_i

      unless Organisation::AREA_TYPES.include?(type)
        flash[:alert] = "Invalid organisation type: #{type}"
        type = PafsCore::Area::RMA_AREA
      end

      @organisations = Organisation.all
      @organisations = @organisations.where(area_type: type) if type.present?
      @organisations = @organisations.where("name ILIKE ?", "%#{q}%") if q.present?
      @organisations = @organisations.order(name: "asc").page(page)
    end

    def new
      @organisation = Organisation.new

      if params[:type]
        if params[:type].empty?
          flash[:alert] = t("select_organisation_type")
        else
          @organisation.area_type = params[:type]
        end
      end

      render org_template(@organisation)
    end

    def edit
      render org_template(@organisation, :edit)
    end

    def create
      @organisation = Organisation.new(organisation_params)

      if @organisation.valid?
        @organisation.save
        redirect_to admin_organisations_path(type: @organisation.area_type)
      else
        render org_template(@organisation)
      end
    end

    def update
      @organisation.update(organisation_params)

      if @organisation.valid?
        @organisation.save
        redirect_to admin_organisations_path(type: @organisation.area_type)
      else
        render org_template(@organisation, :edit)
      end
    end

    private

    def org_template(org, action = :new)
      type = case org.area_type
             when Organisation::RMA_AREA
               "_rma"
             when Organisation::PSO_AREA
               "_pso"
             when Organisation::AUTHORITY
               "_authority"
             else
               ""
             end
      action == :new ? :"new#{type}" : :"edit#{type}"
    end

    def set_organisation
      @organisation = Organisation.find(params[:id])
    end

    def organisation_params
      params.require(:organisation).permit(:name,
                                           :parent_id,
                                           :area_type,
                                           :sub_type,
                                           :identifier,
                                           :end_date)
    end
  end
end

app/views/admin/organisations/_form_authority.html.erb
<%= pafs_form_for [:admin, @organisation] do |f| %>
  <%= csrf_meta_tags %>

  <%= f.hidden_field :area_type %>

  <div class="govuk-grid-row govuk-body">
    <div class="govuk-grid-column-two-thirds">
      <%= f.govuk_text_field :identifier, width: "three-quarters", label: { text: t(".identifier") } %>
    </div>
  </div>

  <div class="govuk-grid-row govuk-body">
    <div class="govuk-grid-column-two-thirds">
      <%= f.govuk_text_field :name, width: "three-quarters", label: { text: t(".name") } %>
    </div>
  </div>

  <div class="govuk-grid-row govuk-body">
    <div class="govuk-grid-column-two-thirds">
      <%= f.label :end_date, t(".end_date") %><br>
      <%= f.date_field :end_date, class: "govuk-select govuk-grid-column-three-quarters" %>
    </div>
  </div>

  <div class="govuk-grid-row govuk-body">
    <div class="govuk-grid-column-two-thirds">
      <%= f.govuk_submit t("continue_label") %>
    </div>
  </div>
<% end %>

app/views/admin/organisations/_form_pso.html.erb
<%= pafs_form_for [:admin, @organisation] do |f| %>
  <%= csrf_meta_tags %>

  <%= f.hidden_field :area_type %>

  <div class="govuk-grid-row govuk-body">
    <div class="govuk-grid-column-two-thirds">
      <%= f.govuk_text_field :name, width: "three-quarters", label: { text: t(".name") } %>
    </div>
  </div>

  <div class="govuk-grid-row govuk-body">
    <div class="govuk-grid-column-two-thirds">
      <%= f.govuk_select :parent_id,
                ea_grouped_areas,
                label: { text: t(".parent_id") },
                options: { prompt: t(".parent_id_prompt") },
                class: "govuk-select govuk-grid-column-three-quarters"  
      %>
    </div>
  </div>

  <div class="govuk-grid-row govuk-body">
    <div class="govuk-grid-column-two-thirds">
      <%= f.govuk_select :sub_type,
                grouped_rfcc_codes,
                label: { text: t(".sub_type") },
                options: { prompt: t(".sub_type_prompt") },
                class: "govuk-select govuk-grid-column-three-quarters"  
      %>
    </div>
  </div>

  <div class="govuk-grid-row govuk-body">
    <div class="govuk-grid-column-two-thirds">
      <%= f.label :end_date, t(".end_date") %><br>
      <%= f.date_field :end_date, class: "govuk-select govuk-grid-column-three-quarters" %>
    </div>
  </div>

  <div class="govuk-grid-row govuk-body">
    <div class="govuk-grid-column-two-thirds">
      <%= f.govuk_submit t("continue_label") %>
    </div>
  </div>
<% end %>

app/views/admin/organisations/_form_rma.html.erb
<%= pafs_form_for [:admin, @organisation] do |f| %>
  <%= csrf_meta_tags %>

  <%= f.hidden_field :area_type %>

  <div class="govuk-grid-row govuk-body">
    <div class="govuk-grid-column-two-thirds">
      <%= f.govuk_text_field :name, width: "three-quarters", label: { text: t(".name") } %>
    </div>
  </div>

  <div class="govuk-grid-row govuk-body">
    <div class="govuk-grid-column-two-thirds">
      <%= f.govuk_text_field :identifier, width: "three-quarters", label: { text: t(".identifier") } %>
    </div>
  </div>

  <div class="govuk-grid-row govuk-body">
    <div class="govuk-grid-column-two-thirds">
      <%= f.govuk_select :sub_type,
                grouped_authority_types,
                label: { text: t(".sub_type") },
                options: { prompt: t(".sub_type_prompt") },
                class: "govuk-select govuk-grid-column-three-quarters"  
      %>
    </div>
  </div>

  <div class="govuk-grid-row govuk-body">
    <div class="govuk-grid-column-two-thirds">
      <%= f.govuk_select :parent_id,
                pso_grouped_areas,
                label: { text: t(".parent_id") },
                options: { prompt: t(".parent_id_prompt") },
                class: "govuk-select govuk-grid-column-three-quarters"  
      %>
    </div>
  </div>

  <div class="govuk-grid-row govuk-body">
    <div class="govuk-grid-column-two-thirds">
      <%= f.label :end_date, t(".end_date") %><br>
      <%= f.date_field :end_date, class: "govuk-select govuk-grid-column-three-quarters" %>
    </div>
  </div>

  <div class="govuk-grid-row govuk-body">
    <div class="govuk-grid-column-two-thirds">
      <%= f.govuk_submit t("continue_label") %>
    </div>
  </div>
<% end %>

app/views/admin/organisations/edit_authority.html.erb
<% content_for :title, t(".heading") %>

<div class="govuk-grid-row govuk-body">

  <h1 class="govuk-heading-l"><%= t(".heading") %></h1>
  <%= render partial: "form_authority" %>
</div>

app/views/admin/organisations/edit_pso.html.erb
<% content_for :title, t(".heading") %>

<div class="govuk-grid-row govuk-body">

  <h1 class="govuk-heading-l"><%= t(".heading") %></h1>
  <%= render partial: "form_pso" %>
</div>

app/views/admin/organisations/edit_rma.html.erb
<% content_for :title, t(".heading") %>

<div class="govuk-grid-row govuk-body">

  <h1 class="govuk-heading-l"><%= t(".heading") %></h1>
  <%= render partial: "form_rma" %>
</div>

app/views/admin/organisations/index.html.erb
<% content_for :title, t(".title") %>

<h1 class="govuk-heading-l"><%= t(".heading_h1") %></h1>
<div class="govuk-grid-row govuk-body">
  <div class="govuk-grid-column-two-thirds">
    <%= form_for admin_organisations_path, method: "get", class: "search-bar" do |f| %>
      <%= label_tag(:q, t(".search_query_label")) %><br/>
      <%= text_field_tag(:q, params[:q] || "", class: "govuk-input govuk-!-width-one-half") %>
      <p>
        <%= label_tag(:type, t(".search_type_label")) %><br/>
        <%= select_tag :type, options_for_select(Organisation::ORGANISATION_TO_AREA_MAPPING, params[:type] || Organisation::RMA_AREA), {class: "govuk-select govuk-!-width-one-half"} %>
      </p>
      <p>
        <%= f.govuk_submit t(".search_btn") %>
      </p>
    <% end %>
  </div>
</div>

<table class="users-table govuk-table govuk-!-font-size-16">
  <caption class="govuk-visually-hidden"><%= t(".heading_table") %></caption> 
  <tbody>
    <tr><td colspan="2"></tr>
    <% @organisations.each do |org| %>
      <tr>
        <td><%= org.name %></td>
        <td><%= link_to t(".edit_link"), edit_admin_organisation_path(org) %>
          <span class="govuk-visually-hidden"> <%= t(".details_for") %> <%= org.name %></span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="govuk-grid-row govuk-body page-nav">
  <div class="govuk-grid-column-one-third">
    <%= page_entries_info @organisations %>
  </div>
  <div class="govuk-grid-column-two-thirds">
    <div class="pagination-area">
      <%= paginate @organisations, left: 0, right: 0, window: 2 %>
    </div>
  </div>
</div>

app/views/admin/organisations/new.html.erb
<% content_for :title, t(".heading_h1") %>

<div class="govuk-grid-row govuk-body">

  <h1 class="govuk-heading-l"><%= t(".heading_h1") %></h1>

  <div class="govuk-grid-row govuk-body">
    <div class="govuk-grid-column-two-thirds">
      <%= form_for new_admin_organisation_path, method: "get", class: "search-bar" do |f| %>
        <%= label_tag(:type, t(".organisation_type_label")) %><br/>
        <%= select_tag :type, options_for_select(Organisation::ORGANISATION_TO_AREA_MAPPING, params[:type]), {class: "govuk-select govuk-!-width-one-half", include_blank: t(".organisation_type_label")} %>
        <p>
          <%= f.govuk_submit t(".submit_btn") %>
        </p>
      <% end %>
    </div>
  </div>

</div>

app/views/admin/organisations/new_authority.html.erb
<% content_for :title, t(".heading") %>

<div class="govuk-grid-row govuk-body">

  <h1 class="govuk-heading-l"><%= t(".heading") %></h1>
  <%= render partial: "form_authority" %>
</div>

app/views/admin/organisations/new_pso.html.erb
<% content_for :title, t(".heading") %>

<div class="govuk-grid-row govuk-body">

  <h1 class="govuk-heading-l"><%= t(".heading") %></h1>
  <%= render partial: "form_pso" %>
</div>

app/views/admin/organisations/new_rma.html.erb
<% content_for :title, t(".heading") %>

<div class="govuk-grid-row govuk-body">

  <h1 class="govuk-heading-l"><%= t(".heading") %></h1>
  <%= render partial: "form_rma" %>
</div>