config/routes.rb
# frozen_string_literal: true

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  namespace :admin do
    namespace :api do
      post "project/status" => "status_updates#create"
    end

    resource :download, only: %i[show create]
    resource :download_all_users, only: [:show]
    resource :download_all_rmas, only: [:show]

    resources :failed_submissions, only: :index do
      member do
        put :mark_as_submitted
        put :retry_submission
      end
    end

    resources :projects do
      member do
        get :edit
        patch :save
      end
    end

    resources :user_areas, only: [:destroy]
    resources :users do
      member do
        get :reinvite
      end
    end
    resources :confirmations, only: [:index]
    resources :camc3, only: [:show], controller: :camc3
    resources :organisations, only: %i[index new create edit update]
  end
  devise_for :users, controllers: { passwords: "passwords" }

  get "/password/reset" => "reset_password#reset", as: :after_password_reset

  mount PafsCore::Engine, at: "/pc"

  match "(errors)/:status", to: PafsCore::Engine, via: :all, constraints: { status: /\d{3}/ }

  root "admin/users#index"
end
# rubocop:enable Metrics/BlockLength

app/models/user.rb
# frozen_string_literal: true

class User < PafsCore::User
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, # :registerable, :rememberable
         :recoverable, :trackable, :validatable, :timeoutable,
         :invitable, validate_on_invite: true

  validate :the_last_admin_isnt_disabled

  accepts_nested_attributes_for :user_areas
  paginates_per 10

  def active_for_authentication?
    admin? && !disabled?
  end

  def inactive_message
    if disabled?
      "You must register for an account before using this service"
    elsif !admin?
      "You must be an administrator to use this service"
    end
  end

  def self.search(term)
    qq = "%#{term}%"
    table = arel_table
    User.includes(:areas)
        .where(table[:first_name].matches(qq)
            .or(table[:last_name].matches(qq))
            .or(table[:email].matches(qq)))
  end

  def self.admins
    where(admin: true)
  end

  def self.active
    where(disabled: false)
  end

  private

  def the_last_admin_isnt_disabled
    return unless (admin_changed?(to: false) || disabled_changed?(to: true)) && !other_admins_exist?

    errors.add(:base, "^Ensure at least one adminstrator is available")
  end

  def other_admins_exist?
    User.where.not(id: id).admins.active.any?
  end
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

module Admin
  # rubocop:disable Metrics/ClassLength
  class UsersController < ApplicationController
    before_action :authenticate_user!

    def index
      q = params.fetch(:q, nil)
      o = params.fetch(:o, nil)
      d = params.fetch(:d, "asc")
      page = params.fetch(:page, "1").to_i

      d = "asc" if d != "asc" && d != "desc"
      @users = if q
                 User.search(q)
               else
                 User.includes(:areas)
               end
      @users = if o && o == "area"
                 @users.joins(:areas).merge(PafsCore::Area.order(name: d)).page(page)
               else
                 @users.order(last_name: d, first_name: d).page(page)
               end
    end

    def show
      @user = User.find(params[:id])
    end

    def new
      @user = User.new
      @user.user_areas.build(primary: true)
      number_of_total_areas = (3 - @user.user_areas.count).to_i
      number_of_total_areas.times do
        @user.user_areas.build
      end
    end

    def edit
      @user = User.find(params[:id])
      number_of_total_areas = (4 - @user.user_areas.size).to_i
      number_of_total_areas.times do
        @user.user_areas.build
      end
    end

    def create
      # Calling User.invite! seems to use find_or_create under the covers which results in
      # it updating an existing user rather than rejecting a duplicate email address
      # So we're creating the user first and inviting if valid
      p = user_params.merge(password: Devise.friendly_token.first(8))

      params = param_clean(p)
      user_areas_attributes = params["user_areas_attributes"]
      user_areas_attributes.each do |index, user_area|
        params["user_areas_attributes"].delete(index) if user_area["area_id"].blank? && user_area["primary"] != "true"
      end
      @user = User.create(params)

      if @user.valid?
        # invite the user
        invite_user(@user)
        redirect_to admin_users_path
      else
        number_of_total_areas = (4 - @user.user_areas.size).to_i
        unless @user.valid?
          number_of_total_areas.times do
            @user.user_areas.build
          end
        end
        render :new
      end
    end

    def update
      @user = User.find(params[:id])

      params = param_clean(user_params)
      user_areas_attributes = params["user_areas_attributes"]
      user_areas_attributes.each do |index, user_area|
        params["user_areas_attributes"].delete(index) if user_area["area_id"].blank? && user_area["primary"] != "true"
      end
      params[:admin] = true if params[:admin]

      if @user.update!(params)
        redirect_to admin_users_path
      else
        number_of_total_areas = (4 - @user.user_areas.size).to_i
        unless @user.valid?
          number_of_total_areas.times do
            @user.user_areas.build
          end
        end
        render "edit"
      end
    end

    def destroy
      @user = User.find(params[:id])

      if @user.destroy
        redirect_to admin_users_path, flash: { notice: "User deleted" }
      else
        redirect_to admin_users_path, flash: { alert: "Could not delete user" }
      end
    end

    def reinvite
      @user = User.find(params[:id])
      invite_user(@user)
      redirect_to edit_admin_user_path(@user)
    end

    private

    def user_params
      params.require(:user).permit(:first_name,
                                   :last_name,
                                   :email,
                                   admin: [],
                                   user_areas_attributes: %i[id area_id user_id primary])
    end

    def param_clean(params)
      params.delete_if do |_k, v|
        param_clean(v) if v.instance_of?(ActionController::Parameters)
        v.empty?
      end
    end

    def invite_user(user)
      user.invite!(current_user) do |u|
        u.skip_invitation = true
      end
      AccountRequestMailer.account_created_email(user).deliver_now
      user.update!(invitation_sent_at: Time.now.utc)
    end

    def navigator
      @navigator ||= PafsCore::ProjectNavigator.new current_resource
    end
  end
  # rubocop:enable Metrics/ClassLength
end

app/views/admin/users/_form.html.erb
<%= pafs_form_for [:admin, @user] do |f| %>
  <%= csrf_meta_tags %>

  <div class="govuk-grid-row govuk-body">
    <div class="govuk-grid-column-two-thirds">
      <%= f.govuk_text_field :first_name, width: "three-quarters", label: { text: t(".first_name") } %>
    </div>
  </div>

  <div class="govuk-grid-row govuk-body">
    <div class="govuk-grid-column-two-thirds">
      <%= f.govuk_text_field :last_name, width: "three-quarters", label: { text: t(".last_name") } %>
    </div>
  </div>

  <div class="govuk-grid-row govuk-body">
    <div class="govuk-grid-column-two-thirds">
      <%= f.govuk_text_field :email, width: "three-quarters", label: { text: t(".email") } %>
    </div>
  </div>

  <div class="govuk-grid-row govuk-body">
    <div class="govuk-grid-column-two-thirds">
      <%= f.fields_for :user_areas do |uaf| %>
        <div class="govuk-grid-row">
          <div class="govuk-grid-column-full">
            <%= uaf.hidden_field :primary %>
            <%= uaf.hidden_field :user_id %>
            <div class="govuk-grid-row">
              <div class="govuk-grid-column-one-half">
                <label class="govuk-label" for="user_user_areas_attributes_<%= uaf.index %>_area_id"><%= area_label(uaf.index) %></label>
              </div>
              <% if uaf.object.id && uaf.index >= 1 %>
                <div class="govuk-grid-column-one-half">
                <div class="add-link govuk-grid-column-three-quarters">
                  <%= link_to("remove", main_app.admin_user_area_path(uaf.object), data: {:confirm => 'Are you sure?'}, :method => :delete) %>
               </div>
               </div>
              <% end %>
            </div>
            <%=
              uaf.select :area_id,
                grouped_options_for_select(determine_grouped_area(uaf.index, @user), uaf.object.area_id),
                { prompt: "Select an area", label: "#{area_label(uaf.index)}", :include_blank => true },
                { class: "govuk-select govuk-grid-column-three-quarters area-select" }
            %>
            <p><br>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="govuk-grid-row govuk-body">
    <div class="govuk-grid-column-full">
      <%= f.govuk_check_box :admin, :admin, label: { text: t(".admin_label") } %>
    </div>
  </div>

  <% if action_name != "new" && @user.persisted? %>
    <div class="form-group">
      <div class="govuk-grid-row govuk-body with-headroom">
        <div class="govuk-grid-column-two-thirds">
          <strong><%= f.label :invitation_sent_at %></strong><br>
          <%= date_or @user.invitation_sent_at, "Not set" %>
        </div>
      </div>
      <div class="govuk-grid-row govuk-body with-headroom">
        <div class="govuk-grid-column-two-thirds">
          <strong><%= f.label :invitation_accepted_at %></strong><br>
          <%= date_or @user.invitation_accepted_at, "Not accepted" %><br>
        </div>
      </div>
      <div class="govuk-grid-row govuk-body with-headroom">
        <div class="govuk-grid-column-two-thirds">
          <strong><%= f.label :last_sign_in_at %></strong><br>
          <%= date_or @user.last_sign_in_at, "Never" %>
        </div>
      </div>
    </div>
  <% end -%>

  <div class="govuk-grid-row govuk-body">
    <div class="govuk-grid-column-two-thirds">
      <%= f.govuk_submit t("save_label") %>
      <%= link_to t("cancel_label"), admin_users_path, class: 'govuk-button govuk-button--secondary horiz-1em-left' %>
      <% if action_name != "new" && @user.persisted? && @user.last_sign_in_at.nil? && @user.invitation_accepted_at.nil? %>
        <div class="resend-link">
          <%= link_to "Resend invitation", reinvite_admin_user_path(@user) %>
        </div>
      <% end -%>

      <% if @user.persisted? %>
        <div class="delete-link">
          <%= link_to "Delete User", admin_user_path(@user), method: :delete, data: { confirm: "Are you sure you want to delete this user?" } %>
        </div>
      <% end%>
    </div>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<% content_for :title, "Edit User" %>

<h1 class="govuk-heading-l">Edit User</h1>
<%= render partial: "form" %>

app/views/admin/users/index.html.erb
<% content_for :title, "Manage users" %>

<h1 class="govuk-heading-l">Manage users</h1>
<div class="govuk-grid-row govuk-body">
  <div class="govuk-grid-column-two-thirds">
    <%= form_for admin_users_path, method: "get", class: "search-bar" do |f| %>
      <%= label_tag(:q, "Search: ") %>
      <%= text_field_tag(:q, params[:q] || "", class: "govuk-input govuk-!-width-one-third") %>
      <%= hidden_field_tag(:o, params[:o]) %>
      <%= hidden_field_tag(:d, params[:d]) %>
      <%= f.govuk_submit "Search" %>
    <% end %>
  </div>
</div>

<table class="users-table govuk-table govuk-!-font-size-16">
  <caption class="govuk-visually-hidden">Users</caption> 
  <thead>
    <tr>
      <th data-sortable="name">Name</th>
      <th data-sortable="email">Email</th>
      <th data-sortable="area">Area</th>
      <th>Admin</th>
      <th>Last sign in</th>
      <th><span class="govuk-visually-hidden">Action</span></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr class="<%= disabled_class(user) %>">
        <td><%= user.full_name %></td>
        <td><%= user.email %></td>
        <td><%= user.primary_area.name %></td>
        <td><%= flag_for user.admin? %></td>
        <td><%= format_last_sign_in_date(user.last_sign_in_at) %></td>
        <td><%= link_to "Edit", edit_admin_user_path(user) %>
          <span class="govuk-visually-hidden"> details for <%= user.full_name %></span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="govuk-grid-row govuk-body page-nav">
  <div class="govuk-grid-column-one-third">
    <%= page_entries_info @users %>
  </div>
  <div class="govuk-grid-column-two-thirds">
    <div class="pagination-area">
      <%= paginate @users, left: 0, right: 0, window: 2 %>
    </div>
  </div>
</div>
<div class="govuk-grid-row govuk-body">
  <div class="govuk-grid-column-one-third actions">
    <%= link_to t("add_user_label"), new_admin_user_path, class: "button" %>
  </div>
  <div class="govuk-grid-column-two-thirds actions">
    <%= link_to t("download_users_label"), admin_download_all_users_path(({:format => :xls})), class: "float-link-right"%>
  </div>
</div>

app/views/admin/users/new.html.erb
<% content_for :title, "Create user" %>

<h1 class="govuk-heading-l">Create User</h1>
<%= render partial: "form" %>