config/routes.rb
# frozen_string_literal: true

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  namespace :admin do
    namespace :api do
      post "project/status" => "status_updates#create"
    end

    resource :download, only: %i[show create]
    resource :download_all_users, only: [:show]
    resource :download_all_rmas, only: [:show]

    resources :failed_submissions, only: :index do
      member do
        put :mark_as_submitted
        put :retry_submission
      end
    end

    resources :projects do
      member do
        get :edit
        patch :save
      end
    end

    resources :user_areas, only: [:destroy]
    resources :users do
      member do
        get :reinvite
      end
    end
    resources :confirmations, only: [:index]
    resources :camc3, only: [:show], controller: :camc3
    resources :organisations, only: %i[index new create edit update]
  end
  devise_for :users, controllers: { passwords: "passwords" }

  get "/password/reset" => "reset_password#reset", as: :after_password_reset

  mount PafsCore::Engine, at: "/pc"

  match "(errors)/:status", to: PafsCore::Engine, via: :all, constraints: { status: /\d{3}/ }

  root "admin/users#index"
end
# rubocop:enable Metrics/BlockLength

app/controllers/admin/failed_submissions_controller.rb
# frozen_string_literal: true

module Admin
  class FailedSubmissionsController < ApplicationController
    before_action :authenticate_user!
    helper_method :projects, :project_sort_order, :project_sort_column

    def mark_as_submitted
      project.update(submitted_to_pol: Time.now.utc)
      redirect_back(fallback_location: root_path)
    end

    def retry_submission
      return redirect_success if submission.perform

      redirect_failure
    end

    private

    def redirect_success
      redirect_back fallback_location: root_path,
                    flash: { notice: "#{project.reference_number} Successfully resubmitted" }
    end

    def redirect_failure
      redirect_back fallback_location: root_path,
                    flash: { alert: "#{project.reference_number} Failed to resubmit" }
    end

    def submission
      @submission ||= PafsCore::Pol::Submission.new(project)
    end

    def scope
      @scope ||= PafsCore::Project.submitted.where(submitted_to_pol: nil)
    end

    def projects
      @projects ||= scope.page(params[:page])
    end

    def project
      return @project if defined?(@project)

      @project = scope.find_by(slug: params[:id])
    end

    def project_sort_column
      params[:sort_col].to_s
    end

    def project_sort_order
      params[:sort_order].to_s
    end
  end
end

app/views/admin/failed_submissions/index.html.erb
<% content_for :title, "Failed PoL Submissions" %>

<div id="dashboard">
  <h1 class="govuk-heading-l">Failed PoL Submissions</h1>
  <p>The following submissions have not been flagged as received by PoL</p>

  <section>
    <% unless projects.empty? %>
      <table class="dashboard">
        <thead>
          <tr>
            <th scope="col" class="project-number">National project number</th>
            <th scope="col" class="sortable-heading">Project name</th>
            <th scope="col">Created by</th>
            <th scope="col">
              <% sort_properties_for_col = get_next_sort_order_and_curr_arrow(project_sort_column, "updated_at", project_sort_order, "updated_at", "desc") %>

              <%= link_to "Last updated", admin_failed_submissions_path(sort_col: "updated_at", sort_order: sort_properties_for_col[:next_sort_order]), class: "sortable-link" %>
              <span class="sortable-arrow"><%=h raw(sort_properties_for_col[:curr_arrow]) %></span>
            </th>

            <th>Actions</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% projects.each do |project| %>
            <tr>
              <td><%= project.reference_number %></td>
              <td><%= project.name %></td>
              <td><%= project.owner.name unless project.owner.blank? %></td>
              <td><%= l(project.updated_at) %></td>
              <td><%= button_to 'Resend to PoL', retry_submission_admin_failed_submission_path(project), method: :put %></td>
              <td><%= button_to 'Proposal in PoL', mark_as_submitted_admin_failed_submission_path(project), method: :put %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
    <div class="govuk-grid-row page-nav">
      <div class="pagination govuk-grid-column-one-third">
        <%= page_entries_info projects %>
      </div>
      <div class="govuk-grid-column-two-thirds">
        <div class="pagination-area">
          <%= paginate projects, left: 0, right: 0, window: 2 %>
        </div>
      </div>
      <% if projects.empty? %>
        <div class="govuk-grid-column-three-quarters">
          <p>There are no failed submissions</p>
        </div>
      <% end %>

      <div class="govuk-grid-column-three-quarters">
        <details role="group">
          <summary role="button" aria-controls="failed-submissions-help">
            <span class="summary">How to manage failed submissions</span>
          </summary>
          <div class="panel panel-indent panel-border-narrow" id="failed-submissions-help">
            <p>Check if the proposal has arrived in PoL</p>

            <ul class='instructions'>
              <li>If YES, click on the 'Proposal in PoL' button.<br/>The proposal will disappear from the list, end of process.</li>
              <li>
                If NO, click on the 'Resend to PoL' button<br/>
                If displays successfully resubmitted, end of process.<br/>
                If displays failed to resubmit, the resend was unsuccessful
                <ul class='instructions'>
                  <li>
                    For unsuccessful resends, please contact the Program Framework helpdesk<br/>
                    <%= link_to nil, 'mailto:helpdesk@programframework.com' %>
                  </li>
                  <li>
                    Also copy into the email the Asset Management Business Systems Team<br/>
                    <%= link_to nil, 'mailto:AssetManagementTeam@environment-agency.gov.uk' %>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
        </details>
      </div>
    </div>
  </section>
</div>